server:
  port : 8081
  servlet:
    context-path: /api

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/onboarding
    username: postgres
    password: adminroot
  # ensure ddl-auto is validate/false & generate-ddl: false
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #default value flyway set to false
  flyway:
    enabled: false
  jackson:
    time-zone: Asia/Jakarta

#logbook style: https://github.com/zalando/logbook#configuration
logbook:
  format:
    style: splunk

logging:
  level:
    #set for openfeign write into log
    org.ait.project.guideline.example.shared.openfeign: DEBUG
    #set for logbook write into log
    org.zalando.logbook: TRACE

feign:
  #active openfeign fallback set true on circuit breaker and hystrix
  circuitbreaker:
    enabled: true
  hystrix:
    enabled: true
  #client openfeign log set
  client:
    config:
      jsonplaceholder-client:
        loggerLevel: full
      reqres-client:
        loggerLevel: full

#turn off time out hystrix, because for default this config if true set timeout to 15 sec, and openfeign timeout unused
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
