CREATE TABLE res_customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   customer_code VARCHAR(255) NOT NULL,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   phone_number VARCHAR(255) NOT NULL,
   address VARCHAR(255) NOT NULL,
   create_date TIMESTAMP with time zone,
   write_date TIMESTAMP with time zone,
   CONSTRAINT pk_res_customer PRIMARY KEY (id)
);

ALTER TABLE res_customer ADD CONSTRAINT uc_res_customer_address UNIQUE (address);

ALTER TABLE res_customer ADD CONSTRAINT uc_res_customer_customer_code UNIQUE (customer_code);

ALTER TABLE res_customer ADD CONSTRAINT uc_res_customer_email UNIQUE (email);

ALTER TABLE res_customer ADD CONSTRAINT uc_res_customer_name UNIQUE (name);

ALTER TABLE res_customer ADD CONSTRAINT uc_res_customer_phone_number UNIQUE (phone_number);