CREATE TABLE res_merchant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   merchant_code VARCHAR(255) NOT NULL,
   name VARCHAR(255) NOT NULL,
   create_date TIMESTAMP with time zone,
   write_date TIMESTAMP with time zone,
   CONSTRAINT pk_res_merchant PRIMARY KEY (id)
);

ALTER TABLE res_merchant ADD CONSTRAINT uc_res_merchant_merchant_code UNIQUE (merchant_code);

ALTER TABLE res_merchant ADD CONSTRAINT uc_res_merchant_name UNIQUE (name);