CREATE TABLE res_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   no_reff VARCHAR(255) NOT NULL,
   res_customer_id BIGINT NOT NULL,
   res_merchant_id BIGINT NOT NULL,
   total INTEGER NOT NULL,
   status VARCHAR(255) NOT NULL,
   customer_email VARCHAR(255) NOT NULL,
   customer_phone VARCHAR(255) NOT NULL,
   customer_address VARCHAR(255) NOT NULL,
   payment_channel VARCHAR(255),
   create_date TIMESTAMP with time zone,
   write_date TIMESTAMP with time zone,
   CONSTRAINT pk_res_order PRIMARY KEY (id)
);

ALTER TABLE res_order ADD CONSTRAINT uc_res_order_no_reff UNIQUE (no_reff);

ALTER TABLE res_order ADD CONSTRAINT FK_RES_ORDER_ON_RES_CUSTOMER FOREIGN KEY (res_customer_id) REFERENCES res_customer (id);

ALTER TABLE res_order ADD CONSTRAINT FK_RES_ORDER_ON_RES_MERCHANT FOREIGN KEY (res_merchant_id) REFERENCES res_merchant (id);