CREATE TABLE res_product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_code VARCHAR(255) NOT NULL,
   product_name VARCHAR(255) NOT NULL,
   product_qty VARCHAR(255) NOT NULL,
   res_merchant_id BIGINT NOT NULL,
   create_date TIMESTAMP with time zone,
   write_date TIMESTAMP with time zone,
   CONSTRAINT pk_res_product PRIMARY KEY (id)
);

ALTER TABLE res_product ADD CONSTRAINT uc_res_product_product_code UNIQUE (product_code);

ALTER TABLE res_product ADD CONSTRAINT uc_res_product_product_name UNIQUE (product_name);

ALTER TABLE res_product ADD CONSTRAINT FK_RES_PRODUCT_ON_RES_MERCHANT FOREIGN KEY (res_merchant_id) REFERENCES res_merchant (id);