CREATE TABLE res_order_line (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   order_id BIGINT NOT NULL,
   product_code VARCHAR(255) NOT NULL,
   product_name VARCHAR(255) NOT NULL,
   product_qty INTEGER NOT NULL,
   sub_total INTEGER NOT NULL,
   create_date TIMESTAMP with time zone,
   write_date TIMESTAMP with time zone,
   CONSTRAINT pk_res_order_line PRIMARY KEY (id)
);

ALTER TABLE res_order_line ADD CONSTRAINT FK_RES_ORDER_LINE_ON_ORDER FOREIGN KEY (order_id) REFERENCES res_order (id);